server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: /cambio-service
        uri: lb://cambio-service
        predicates:
        - Path=/cambio-service/**
      - id: /game-service
        uri: lb://game-service
        predicates:
        - Path=/game-service/**
      - id: openapi
        uri: lb://api-gateway
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
  logging:
    pattern:
      level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  management:
    zipkin:
      tracing:
        enpoint: http://localhost:9411/api/v2/spans
    tracing:
      enabled: true
      sampling:
        probability: 1.0
      propagation:
        type: w3c
      baggage:
        enabled: true		




  